### ISSUE TITLE
hot to get Chungus? i cant find a downloadlink from the whole CPU

### ISSUE THREAD

**Issue by zERO123331** [sammyuri/chungus-2-assembler#5]

**Comment by elapt1c** [comment]
i have chungus2. i just got the file. ask sammyuri for the file or i will attach the file here. it is an mchprs world file though so u need to set that up
[world.zip](https://github.com/sammyuri/chungus-2-assembler/files/9277365/world.zip)
.

**Comment by Heroect** [comment]
> 

where do we ask him i asked him on discord and he hasn't responded

**Comment by minecraftredstonegod** [comment]
I cant use the world on mchprs it gives the error:

plot panicked at crates\core\src\plot\mod.rs:1262:25:
error loading plot 0,0

Caused by:
    0: error loading plot save file at ./world/plots/p0,0
    1: invalid plot data header
   0: alloc::boxed::convert::impl$17::from::impl$1::fmt
   1: aws_lc_0_38_0_EVP_MD_size
   2: std::panicking::panic_with_hook
             at /rustc/ac68faa20c58cbccd01ee7208bf3b6e93a7d7f96/library\std\src\panicking.rs:833
   3: std::panicking::panic_handler::closure$0
             at /rustc/ac68faa20c58cbccd01ee7208bf3b6e93a7d7f96/library\std\src\panicking.rs:698
   4: std::sys::backtrace::__rust_end_short_backtrace<std::panicking::panic_handler::closure_env$0,never$>
             at /rustc/ac68faa20c58cbccd01ee7208bf3b6e93a7d7f96/library\std\src\sys\backtrace.rs:182
   5: std::panicking::panic_handler
             at /rustc/ac68faa20c58cbccd01ee7208bf3b6e93a7d7f96/library\std\src\panicking.rs:689
   6: core::panicking::panic_fmt
             at /rustc/ac68faa20c58cbccd01ee7208bf3b6e93a7d7f96/library\core\src\panicking.rs:80
   7: core::fmt::num::impl$34::fmt
   8: aws_lc_0_38_0_EVP_MD_size
   9: std::sys::thread::windows::impl$0::new::thread_start
             at /rustc/ac68faa20c58cbccd01ee7208bf3b6e93a7d7f96/library\std\src\sys\thread\windows.rs:58
  10: BaseThreadInitThunk
  11: RtlUserThreadStart
